apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodeapp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodeapp
    app.kubernetes.io/part-of: test-application
  name: nodeapp
  namespace: hacbs
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nodeapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nodeapp
    spec:
      containers:
      - image: quay.io/karthik_jk/nodeapp@sha256:dd5995f11a6c43f7a268ddf6690d3160afae9c172156f3028fb23504be77695b
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
